   name: CI
   on: [push]
   jobs:
     call-ci:
       uses: kk-security-jpvardhan/.github/.github/workflows/reusable-ci.yml@main
       with:
         node-version: '20'
       secrets:
         NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
